### ISSUE TITLE
OOC Emojis do not work

### ISSUE THREAD

**Issue by VladinXXV** [Towelstation13/towelstation13#24]
Reporting client version: 514.1589

## Round ID:
[95](https://scrubby.melonmesa.com/round/95)

## Reproduction:
![image](https://github.com/Towelstation13/towelstation13/assets/44104681/a50aa2db-116e-46a0-b77c-6e29f09ab19b)

**Comment by SapphoQueer** [comment]
UGH FINE IM RE-ENABLING IT IN THE CONFIG
