### ISSUE TITLE
Character Creation page body_size is not recognized

### ISSUE THREAD

**Issue by VladinXXV** [Towelstation13/towelstation13#27]
Reporting client version: 514.1589

## Round ID:
[104](https://scrubby.melonmesa.com/round/104)

## Reproduction:
On character creation page:
![image](https://github.com/Towelstation13/towelstation13/assets/44104681/879b11d4-7ea4-4443-8a7b-286f3bb39f7a)

**Comment by xPokee** [comment]
Caused by something in https://github.com/Towelstation13/towelstation13/pull/11 checking it out.
