### ISSUE TITLE
Runtime(\ "undefined proc or verb /mob/dead/new_player/toggle move intent().\\n\")

### ISSUE THREAD

**Issue by xPokee** [Towelstation13/towelstation13#28]
## Round ID:
N/A

## Reproduction:
![image](https://github.com/Towelstation13/towelstation13/assets/20053168/24acd1dd-9393-45e5-8e40-a295e9bd4414)
![image](https://github.com/Towelstation13/towelstation13/assets/20053168/694c2392-b5af-48df-8e40-6e6fd389ecd6)

**Comment by xPokee** [comment]
Fix PR made https://github.com/tgstation/tgstation/pull/78384

**Comment by distributivgesetz** [comment]
unrelated runtime in title?
